development:
  adapter: postgresql
  encoding: unicode
  database: taxi_service_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: taxi_service_test
  pool: 5
  username:
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: taxi_service_production
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>